spring:
  application:
    name: aiTalk
    version: 1.0.0
  datasource:
    url: jdbc:mysql://14.103.183.242:3366/qN?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  data:
    redis:
      host: 14.103.183.242
      port: 6376
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
server:
  port: 8090

ai :
  key : sk-90e295249b264fbe9e2dfe9d84dc06dd
  base-url: ""
