spring:
  application:
    name: aiTalk
    version: 1.0.0
  datasource:
#    url: jdbc:mysql://14.103.183.242:3366/qN?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
#    username: admin
#    password: admin
    url: jdbc:mysql://127.0.0.1:3306/aitalk?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  data:
    redis:
      host: 14.103.183.242
      port: 6376
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  ai:
    openai:
      api-key: ${BL_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: deepseek-v3


server:
  port: 8090

ai:
  apikey: ${BL_API_KEY}


logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.yyxxlu.aitalk: debug